import { readFileSync } from "node:fs";
import { attachContinuation } from "./continuation-fixture.mjs";

const CONTRACT=JSON.parse(readFileSync(new URL("../src/direct-route-contract.json",import.meta.url),"utf8"));
const PREPARE="https://api.assetfare.dev/v2/prepare",SESSION="https://api.assetfare.dev/v2/session";
const REQUEST_FIELDS=["caller_approved","from_chain","from_token","to_chain","to_token","amount_usd","wallets","event_signer_public"];
const prepareOption={kind:"one_shot_first_unsigned_bundle",method:"POST",url:PREPARE,requires_explicit_caller_approval:true,requires_public_wallet_addresses:true,assetfare_never_signs_submits_or_auto_calls:true,note:"Stateless first unsigned bundle."};
const lifecycle={create:{method:"POST",url:SESSION},read:{method:"GET",url:`${SESSION}/{session_id}`},observe_source:{method:"POST",url:`${SESSION}/{session_id}/observe-source`},observe_output:{method:"POST",url:`${SESSION}/{session_id}/observe-output`},refresh_action:{method:"POST",url:`${SESSION}/{session_id}/refresh-action`}};
const sessionOption={kind:"caller_approved_full_workflow_session",method:"POST",url:SESSION,lifecycle_urls:lifecycle,requires_explicit_caller_approval:true,requires_public_wallet_addresses:true,assetfare_never_signs_submits_or_auto_calls:true,note:"Receipt-driven workflow."};
function handoff(){return {kind:"caller_operated_rest_prepare",url:PREPARE,method:"POST",requires_explicit_caller_approval:true,requires_public_wallet_addresses:true,request_fields:REQUEST_FIELDS,assetfare_server_signing:false,assetfare_server_submission:false,caller_must_verify_sign_and_submit:true,requires_fresh_requote:true,automatic_prepare_call_forbidden:true,options:[structuredClone(prepareOption),structuredClone(sessionOption)],note:"Explicit caller operation only.",available:true};}
function handoffV2(){return {kind:"caller_operated_rest_prepare",url:PREPARE,method:"POST",requires_explicit_caller_approval:true,requires_public_wallet_addresses:true,request_fields:REQUEST_FIELDS,assetfare_server_signing:false,assetfare_server_submission:false,caller_must_verify_sign_and_submit:true,requires_fresh_requote:true,automatic_prepare_call_forbidden:true,schema_version:2,selection:"choose_exactly_one",mutually_exclusive:true,do_not_call_both:true,selection_before_signing:true,once_any_action_submitted_do_not_start_other_mode:true,enforcement:"advisory_caller_side",options:[{...structuredClone(prepareOption),preview_or_manual_first_action_only:true,not_a_session:true,do_not_start_session_after_submission:true},{...structuredClone(sessionOption),recommended_for_multistep:true}],note:"Explicit mutually exclusive choice.",available:true};}

export function quoteFixture({from_chain="base",from_token="USDC",to_chain="arbitrum",to_token="USDC",amount_usd=1000,quote_id="00000000-0000-4000-8000-000000000001",issuedAt=Date.now()}={}){
  const routeName=`${from_chain}:${from_token}->${to_chain}:${to_token}`,plan=CONTRACT.routes[routeName];if(!plan)throw new Error("fixture_route_invalid");
  let expectedInput=Math.round(amount_usd*1_000_000),minimumInput=expectedInput;const raw=[],summary=[];
  for(const step of plan.steps){
    const expectedOutput=Math.max(1,expectedInput-1000),minimumOutput=Math.max(1,minimumInput-2000),[fc,fa]=step.from.split(":"),[tc,ta]=step.to.split(":"),evidence={status:"pass",inputAmount:String(expectedInput),aggregatorApiUsed:false,signed:false,submitted:false};let base;
    if(step.action==="swap")base={kind:"direct_swap",chain:fc,provider:step.provider,from:fa,to:ta,route_fee_bps:step.assetfare_fee_bps};
    else if(step.provider==="across_intent_bridge")base={kind:"direct_bridge",provider:step.provider,from:fc,to:tc,from_asset:fa,to_asset:ta,external_intent_protocol:true,route_fee_bps:step.assetfare_fee_bps};
    else base={kind:"direct_bridge",provider:step.provider,from:fc,to:tc,asset:fa,...(step.provider==="circle_cctp"&&["polygon","optimism"].includes(fc)?{cctp_mode:"no_forward",finality_threshold:2000,destination_native_gas_required:true,economics_informational_only:true}:{}),route_fee_bps:step.assetfare_fee_bps};
    raw.push({index:step.index,...base,expected_input_base:expectedInput,floor_input_base:minimumInput,expected_output_base:expectedOutput,minimum_output_base:minimumOutput,expected_evidence:evidence,floor_evidence:null});
    summary.push({...step,expected_input_base:String(expectedInput),minimum_input_base:String(minimumInput),expected_output_base:String(expectedOutput),minimum_output_base:String(minimumOutput),aggregator_api_used:false});expectedInput=expectedOutput;minimumInput=minimumOutput;
  }
  const expectedReceive=expectedInput/1_000_000,minimumReceive=minimumInput/1_000_000,expectedCost=Math.max(0,amount_usd-expectedReceive),maximumCost=Math.max(0,amount_usd-minimumReceive),feeIndex=plan.steps.findIndex((step)=>step.assetfare_fee_bps===1),external=plan.classification==="external_intent",small=maximumCost/amount_usd>=.01;
  return attachContinuation({quote_id,status:"capped_public_agent_release",version:"assetfare-direct-multichain-api-quote-v2",as_of:new Date(issuedAt).toISOString(),ttl_seconds:60,intent:{from:`${from_chain}:${from_token}`,to:`${to_chain}:${to_token}`,amount_usd,estimated_input_base:Math.round(amount_usd*1_000_000)},cost_summary:{scope:"token_path_only_network_gas_excluded",input_value_usd:amount_usd,expected_receive_value_usd:expectedReceive,minimum_receive_value_usd:minimumReceive,expected_total_cost_usd:expectedCost,maximum_total_cost_usd:maximumCost,expected_total_cost_percent:expectedCost/amount_usd*100,maximum_total_cost_percent:maximumCost/amount_usd*100,assetfare_service_fee:{bps:1,estimated_usd:Math.min(amount_usd/10000,5),included_in_receive_amount:true,note:"AssetFare service fee only; not total"},provider_fee_components:[],unpriced_costs:["source_chain_network_fee"],rankable_all_in:false,small_amount_warning:small,warning:small?"fixed provider cost":null},eta:{estimated_time_seconds:20,estimated_time_range_seconds:[8,20],complete_route_estimate:true,sources:["https://developers.circle.com/stablecoins/cctp-getting-started"],note:"fixture"},offer:{expected_receive_amount:expectedReceive,estimated_min_receive_amount:minimumReceive,expected_receive_usd:expectedReceive,estimated_min_receive_usd:minimumReceive,output_symbol:to_token,estimated_time_seconds:20,assetfare_fee_bps:1,fee_modeled_bps:1,fee_collectible_now:true,fee_blocker:null,fee_collection_steps:[feeIndex],fee_collection:"only_on_eligible_successful_executor_step"},route:{status:"pass",version:"assetfare-direct-multichain-quote-v2",route:routeName,mode:plan.mode,input_base:Math.round(amount_usd*1_000_000),expected_output_base:expectedInput,minimum_output_base:minimumInput,steps:raw,quote_latency_ms:1,aggregator_api_used:false,external_intent_protocol_used:external,server_signing:false,server_submission:false},direct_route_summary:{version:"assetfare-direct-route-summary-v1",route:routeName,from:`${from_chain}:${from_token}`,to:`${to_chain}:${to_token}`,classification:plan.classification,mode:plan.mode,route_aggregator_used:false,external_intent_protocol_used:external,provider_internal_dex_aggregation_possible:external,assetfare_fee_bps:1,fee_collection_step_index:feeIndex,server_signing:false,server_submission:false,step_count:summary.length,steps:summary},risk:{non_atomic:summary.length>1,fresh_quote_required_each_step:true,external_intent_protocol_used:external,provider_internal_dex_aggregation_possible:external,server_signing:false,server_submission:false},execution:{supported:true,first_unsigned_action_supported:true,future_actions_require_verified_receipts:true,blocker:null},caller_action_plan_handoff:handoff(),caller_action_plan_handoff_v2:handoffV2(),handoff_schema_version:2},{issuedAt});
}
