[Service]
WorkingDirectory=/home/ec2-user/assetfare-mcp-releases/3a33bcf93e0dba2e922bbd4f3c18e4dd920550e3
ExecStart=
ExecStart=/home/ec2-user/.nvm/versions/node/v24.19.0/bin/node /home/ec2-user/assetfare-mcp-releases/3a33bcf93e0dba2e922bbd4f3c18e4dd920550e3/src/server.js
