[Service]
WorkingDirectory=/home/ec2-user/assetfare-mcp-releases/3b3fb0391960b6f01a13bd0a4fde4c71eb9defce
ExecStart=
ExecStart=/home/ec2-user/.nvm/versions/node/v24.19.0/bin/node /home/ec2-user/assetfare-mcp-releases/3b3fb0391960b6f01a13bd0a4fde4c71eb9defce/src/server.js
