import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { allowedHost, createServer, provenanceFromHeaders } from "./server.js";

const server = createServer();
const client = new Client({ name: "assetfare-mcp-selftest", version: "0.1.0" });
const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
await server.connect(serverTransport);
await client.connect(clientTransport);
const result = await client.listTools();
const names = result.tools.map((tool) => tool.name).sort();
const required = ["assetfare_manifest", "assetfare_quote", "assetfare_start_wallet_auth", "assetfare_create_session", "assetfare_observe_destination"];
if (!required.every((name) => names.includes(name))) throw new Error("required MCP tools missing");
const quoteTool = result.tools.find((tool) => tool.name === "assetfare_quote");
if (JSON.stringify(quoteTool?.inputSchema?.properties?.destination_chain?.enum) !== JSON.stringify(["base", "arbitrum"])) throw new Error("quote destination schema mismatch");
if (quoteTool?.inputSchema?.properties?.amount_usd?.minimum !== 1 || quoteTool?.inputSchema?.properties?.amount_usd?.maximum !== 1000) throw new Error("quote amount schema mismatch");
if (names.some((name) => /sign|submit|send/i.test(name))) throw new Error("MCP must not expose transaction submission");
const validProvenance = provenanceFromHeaders({ "x-forwarded-for": "203.0.113.10", "user-agent": "agent-test/1" });
const spoofedProvenance = provenanceFromHeaders({ "x-forwarded-for": "203.0.113.10, 198.51.100.2", "user-agent": "agent-test/1" });
if (validProvenance.requestIdentity !== "203.0.113.10" || spoofedProvenance.requestIdentity) throw new Error("MCP provenance validation failed");
if (!allowedHost("api.assetfare.dev") || !allowedHost("127.0.0.1:8790") || allowedHost("evil.example")) throw new Error("MCP host allowlist failed");
console.log(JSON.stringify({ status: "pass", tool_count: names.length, has_submission_tool: false, provenance_validation: true }));
await client.close();
await server.close();
